language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache:
  - pip
  - $HOME/.cache/pip
install:
  - pip install pipenv
  - pipenv install --system --dev
script:
  - python manage.py test
  - "flake8 ."